### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Salamandar**
Upgrade to 2.8, so bump to Django 4.2
@fallen this is where I'll do the actual merge on master and run the CI.

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by fallen** [comment]
> Upgrade to 2.8, so bump to Django 4.2 @fallen this is where I'll do the actual merge on master and run the CI.

Thanks!

**Comment by fallen** [comment]
You need to update the config.py according to this: https://github.com/pytition/Pytition/commit/c37629925b461c87d9d12c09f18f529222905d07

**Comment by fallen** [comment]
(or maybe I need to do it? :p)

**Comment by Salamandar** [comment]
Fixed ! Merging now, I manually tested this and this works. Thanks @fallen for the hard work <3

**Comment by fallen** [comment]
> Fixed ! Merging now, I manually tested this and this works. Thanks @fallen for the hard work <3

Thanks a lot to you as well :)

**Pull request merged**
